export const REQUEST = "REQUEST";
export const REQUEST_DONE = "REQUEST_DONE";

export const USER_LOGIN_SUCCESS = " USER_LOGIN_SUCCESS";
export const USER_AUTH_FAIL = "USER_AUTH_FAIL";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const SET_LOADING = "SET_LOADING";
export const CLEAR_LOADING = "CLEAR_LOADING";
